version: '3'
services:

  postgres:
    container_name: postgres
    build:
      context: ./backend/postgres
    image: postgres:ft_transcendence
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ft_transcendence
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - ft_transcendence
    ports:
      - 4242:5432

networks:
  ft_transcendence:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./database
