version: '3'
services:

  postgres:
    container_name: postgres
    build:
      context: ./postgres
    image: postgres:ft_transcendence
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - ft_transcendence
    ports:
      - 5432:5432

  django:
    container_name: django
    build:
      context: ./django
    image: django:ft_transcendence
    restart: always
    volumes:
      - django_code:/app
    environment:
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
    driver: bridge

volumes:
  postgres_data:
  django_code: