
services:
  redis:
    container_name: redis
    image: redis
    expose:
      - "6379"
    restart: always

  db:
    container_name: db
    image: postgres:16.2
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  reverse_proxy:
    container_name: nginx
    build: ./nginx
    ports:
      - "1339:443"
    volumes:
      - static_volume:/app/static
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: {}
  static_volume: {}

networks:
  pong:
    driver: bridge
