version: '3'
services:

  postgres:
    container_name: postgres
    build:
      context: ./postgres
    image: postgres:ft_transcendence
    restart: always
    networks:
      - ft_transcendence
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  django:
    container_name: django
    build:
      context: ./django
    image: django:ft_transcendence
    restart: always
    networks:
      - ft_transcendence
    ports:
      - 8000:8000
    volumes:
      - django_code:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

networks:
  ft_transcendence:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./database
  django_code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./srcs
