# Generated by Django 4.2 on 2024-03-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='token_login',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
