# Generated by Django 4.2 on 2024-03-05 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField()),
                ('Age', models.CharField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
