# Generated by Django 4.2 on 2024-03-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpong',
            name='uid',
        ),
    ]
