# Generated by Django 4.2 on 2024-03-05 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_userpong_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpong',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
