# Generated by Django 4.2 on 2024-03-05 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userpong_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpong',
            name='id',
        ),
        migrations.AlterField(
            model_name='userpong',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
