# Generated by Django 4.2 on 2024-04-10 13:44

import app.models.Player
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=app.models.Player.rename_profile_picture, validators=[app.models.Player.validate_profile_picture])),
                ('player_status', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online'), ('Playing', 'Playing')], default='Offline', max_length=22)),
                ('player_elo', models.IntegerField(blank=True, default=None, null=True)),
                ('player_rank', models.CharField(choices=[('UNRANKED', 'UNRANKED'), ('BRONZE', 'BRONZE'), ('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('PLATINIUM', 'PLATINIUM'), ('DIAMOND', 'DIAMOND'), ('ELITE', 'ELITE'), ('CHAMPION', 'CHAMPION'), ('UNREAL', 'UNREAL')], default='UNRANKED', max_length=26)),
                ('total_victories', models.IntegerField(default=0)),
                ('total_defeats', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
