# Generated by Django 4.2 on 2024-03-06 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('points_player_one', models.IntegerField(default=0)),
                ('points_player_two', models.IntegerField(default=0)),
                ('xpos_tournament', models.IntegerField(null=True)),
                ('ypos_tournament', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.SlugField(max_length=24, unique=True)),
                ('login_42', models.SlugField(max_length=12, null=True, unique=True)),
                ('pic', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('elo', models.IntegerField(default=0)),
                ('victories', models.IntegerField(default=0)),
                ('defeats', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Offline'), (1, 'Online'), (2, 'Playing')], default=0)),
                ('token_login', models.TextField(default=uuid.uuid4, null=True, unique=True)),
                ('token_login_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('token_login_end_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('uid_operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uid_operator_set', to='pong.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_Player',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('uid_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uid_player_set', to='pong.player')),
                ('uid_tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uid_tournament_set', to='pong.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('one_to_two_relation', models.IntegerField(choices=[(0, 'None'), (1, 'Friend'), (2, 'Blocked')], default=0)),
                ('two_to_one_relation', models.IntegerField(choices=[(0, 'None'), (1, 'Friend'), (2, 'Blocked')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid_user_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_user_one_set', to='pong.player')),
                ('uid_user_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_user_two_set', to='pong.player')),
            ],
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['username'], name='pong_player_usernam_b35f52_idx'),
        ),
        migrations.AddField(
            model_name='match',
            name='uid_player_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uid_player_one_set', to='pong.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='uid_player_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uid_player_two_set', to='pong.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='uid_tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_set', to='pong.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='uid_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uid_winner_set', to='pong.player'),
        ),
    ]
