# Generated by Django 4.2 on 2024-03-06 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_alter_match_ended_at_alter_match_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=1)),
                ('sended_at', models.DateTimeField(auto_now_add=True)),
                ('uid_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_receiver_set', to='pong.player')),
                ('uid_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_sender_set', to='pong.player')),
            ],
        ),
    ]
