# Generated by Django 5.0.3 on 2024-03-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
