# Generated by Django 4.2 on 2024-03-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_alter_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting_player'), (1, 'in_game'), (2, 'end')], default=0),
        ),
    ]
